<?php

define("API_VERSION", "v1");
define("DEFAULT_PAGE_LIMIT", 25);
define("MAXIMUM_PAGE_LIMIT", 100);
define("CACHE_ENABLED", TRUE);
define("CACHE_LIFETIME_SECONDS", 900);

require_once('api.admin.inc');
require_once('api.render.inc');

/**
 * Implements hook_menu().
 */
function api_menu() {

  $items["api/" . API_VERSION . "/openapi.yaml"] = array(
    'page callback' => '_api_openapi',
    'access arguments' => array('view swagger ui'),
    'type' => MENU_CALLBACK,
  );

  // API
  $items["api/" . API_VERSION . "/reviews"] = array(
    'page callback' => '_api_reviews',
    'access arguments' => array('use rest api'),
    'type' => MENU_CALLBACK,
  );
  $items["api/" . API_VERSION . "/reviews/%"] = array(
    'page callback' => '_api_review',
    'page arguments' => array(3),
    'access arguments' => array('use rest api'),
    'type' => MENU_CALLBACK,
  );
  $items["api/" . API_VERSION . "/concert_reviews"] = array(
    'page callback' => '_api_concert_reviews',
    'access arguments' => array('use rest api'),
    'type' => MENU_CALLBACK,
  );
  $items["api/" . API_VERSION . "/concert_reviews/%"] = array(
    'page callback' => '_api_concert_review',
    'page arguments' => array(3),
    'access arguments' => array('use rest api'),
    'type' => MENU_CALLBACK,
  );
  $items["api/" . API_VERSION . "/concerts"] = array(
    'page callback' => '_api_concerts',
    'access arguments' => array('use rest api'),
    'type' => MENU_CALLBACK,
  );
  $items["api/" . API_VERSION . "/concerts/%"] = array(
    'page callback' => '_api_concert',
    'page arguments' => array(3),
    'access arguments' => array('use rest api'),
    'type' => MENU_CALLBACK,
  );
  $items["api/" . API_VERSION . "/interviews"] = array(
    'page callback' => '_api_interviews',
    'access arguments' => array('use rest api'),
    'type' => MENU_CALLBACK,
  );
  $items["api/" . API_VERSION . "/interviews/%"] = array(
    'page callback' => '_api_interview',
    'page arguments' => array(3),
    'access arguments' => array('use rest api'),
    'type' => MENU_CALLBACK,
  );
  $items["api/" . API_VERSION . "/news"] = array(
    'page callback' => '_api_news',
    'access arguments' => array('use rest api'),
    'type' => MENU_CALLBACK,
  );
  $items["api/" . API_VERSION . "/news/%"] = array(
    'page callback' => '_api_news_story',
    'page arguments' => array(3),
    'access arguments' => array('use rest api'),
    'type' => MENU_CALLBACK,
  );
  $items["api/" . API_VERSION . "/reportages"] = array(
    'page callback' => '_api_reportages',
    'access arguments' => array('use rest api'),
    'type' => MENU_CALLBACK,
  );
  $items["api/" . API_VERSION . "/reportages/%"] = array(
    'page callback' => '_api_reportage',
    'page arguments' => array(3),
    'access arguments' => array('use rest api'),
    'type' => MENU_CALLBACK,
  );
  $items["api/" . API_VERSION . "/artists/%"] = array(
    'page callback' => '_api_artist',
    'page arguments' => array(3),
    'access arguments' => array('use rest api'),
    'type' => MENU_CALLBACK,
  );

  // Vocabulary:
  $items["api/" . API_VERSION . "/genres"] = array(
    'page callback' => '_api_genres',
    'access arguments' => array('use rest api'),
    'type' => MENU_CALLBACK,
  );
  $items["api/" . API_VERSION . "/genres/%"] = array(
    'page callback' => '_api_genre',
    'page arguments' => array(3),
    'access arguments' => array('use rest api'),
    'type' => MENU_CALLBACK,
  );
  $items["api/" . API_VERSION . "/venues"] = array(
    'page callback' => '_api_venues',
    'access arguments' => array('use rest api'),
    'type' => MENU_CALLBACK,
  );
  $items["api/" . API_VERSION . "/venues/%"] = array(
    'page callback' => '_api_venue',
    'page arguments' => array(3),
    'access arguments' => array('use rest api'),
    'type' => MENU_CALLBACK,
  );

  // Administration
  $items['admin/config/api'] = array(
    'title' => t('REST API'),
    'page callback' => '_api_keys_list',
    'access arguments' => array('administer rest api'),
    'file' => 'api.admin.inc',
  );
  $items['admin/config/api/keys'] = array(
    'title' => t('API Keys'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10
  );
  $items['admin/config/api/auth'] = array(
    'title' => t('Auth'),
    'page callback' => '_api_auth_list',
    'access arguments' => array('administer rest api'),
    'file' => 'api.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => -9
  );
  $items["admin/config/api/doc"] = array(
    'title' => t('API Documentation'),
    'description' => t('Swagger UI documentation page for Heavymetal.dk REST API.'),
    'page callback' => '_api_swagger_ui',
    'access arguments' => array('view swagger ui'),
    'type' => MENU_LOCAL_TASK,
    'weight' => -8
  );

  // Admin API key:
  $items['admin/config/api/add_api_key'] = array(
    'title' => 'Add API key',
    'description' => 'Add a new API key.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_add_api_key_form'),
    'access arguments' => array('administer rest api'),
    'type' => MENU_CALLBACK,
    'file' => 'api.admin.inc',
  );
  $items['admin/config/api/edit_api_key/%'] = array(
    'title' => 'Edit API key',
    'description' => 'Edit an existing API key.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_edit_api_key_form', 4),
    'access arguments' => array('administer rest api'),
    'type' => MENU_CALLBACK,
    'file' => 'api.admin.inc',
  );
  $items['admin/config/api/delete_api_key/%'] = array(
    'title' => 'Delete API key',
    'description' => 'Delete an existing API key.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_delete_api_key_form', 4),
    'access arguments' => array('administer rest api'),
    'type' => MENU_CALLBACK,
    'file' => 'api.admin.inc',
  );

  // Admin user:
  $items['admin/config/api/add_user'] = array(
    'title' => 'Add API user',
    'description' => 'Add a new API user.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_add_user_form'),
    'access arguments' => array('administer rest api'),
    'type' => MENU_CALLBACK,
    'file' => 'api.admin.inc',
  );
  $items['admin/config/api/edit_user/%'] = array(
    'title' => 'Edit API user',
    'description' => 'Edit an existing API user.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_edit_user_form', 4),
    'access arguments' => array('administer rest api'),
    'type' => MENU_CALLBACK,
    'file' => 'api.admin.inc',
  );
  $items['admin/config/api/delete_user/%'] = array(
    'title' => 'Delete API user',
    'description' => 'Delete an existing API user.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_delete_user_form', 4),
    'access arguments' => array('administer rest api'),
    'type' => MENU_CALLBACK,
    'file' => 'api.admin.inc',
  );
  return $items;
}

function _valid_http_auth() {
  if (!isset($_SERVER['PHP_AUTH_USER'])) {
    drupal_add_http_header('WWW-Authenticate', 'Basic realm="Heavymetal.dk API"');
    drupal_add_http_header('Status', '401 Unauthorized');
    drupal_json_output(array(
      "errors" => array(
        array(
          "code" => 7,
          "message" => "Authentication information is missing or invalid."
        )
      )
    ));
    return FALSE;
  } else {

    $user = db_query("SELECT * FROM api_users WHERE username = :username AND active = :active LIMIT 1", array(':username' => check_plain($_SERVER['PHP_AUTH_USER']), ':active' => 1))->fetchAssoc();

    if (is_array($user) && password_verify($_SERVER['PHP_AUTH_PW'], $user['password'])) {
      return TRUE;
    } else {
      drupal_add_http_header('Status', '401 Unauthorized');
      drupal_json_output(array(
        "errors" => array(
          array(
            "code" => 7,
            "message" => "Authentication information is missing or invalid."
          )
        )
      ));
      return FALSE;
    }
  }
}

function _valid_api_key() {

  if (!isset($_GET['api_key'])) {
    drupal_add_http_header('Status', '400 Bad Request');
    drupal_json_output(array(
      "errors" => array(
        array(
          "code" => 1,
          "message" => "Invalid parameters. Your request is missing a required parameter."
        )
      )
    ));
    return FALSE;
  }

  $key = db_query("SELECT * FROM api_keys WHERE api_key = :api_key LIMIT 1", array(':api_key' => check_plain($_GET['api_key'])))->fetchAssoc();

  if (!is_array($key)) {
    drupal_add_http_header('Status', '403 Forbidden');
    drupal_json_output(array(
      "errors" => array(
        array(
          "code" => 2,
          "message" => "Invalid API key. You must be granted a valid key."
        )
      )
    ));
    return FALSE;
  }

  if (!$key['active']) {
    drupal_add_http_header('Status', '403 Forbidden');
    drupal_json_output(array(
      "errors" => array(
        array(
          "code" => 3,
          "message" => "Suspended API key. Access for your account has been suspended."
        )
      )
    ));
    return FALSE;
  }

  return TRUE;
}

function _limit() {
  $limit = DEFAULT_PAGE_LIMIT;
  if (isset($_GET['limit']) && is_numeric($_GET['limit'])) {
    if ($_GET['limit'] > MAXIMUM_PAGE_LIMIT) {
      drupal_add_http_header('Status', '403 Forbidden');
      drupal_json_output(array(
        "errors" => array(
          array(
            "code" => 6,
            "message" => "A maximum of " . MAXIMUM_PAGE_LIMIT . " is allowed as page limit."
          )
        )
      ));
      drupal_exit();
    }
    $limit = $_GET['limit'];
  }

  return $limit;
}

function _api_concert_reviews() {
  drupal_add_http_header('Access-Control-Allow-Methods: ', 'GET');

  if (!isset($_GET['api_key'])) {
    if (!_valid_http_auth()) {
      drupal_exit();
    }
  } else {
    if (!_valid_api_key()) {
      drupal_exit();
    }
  }

  $offset = (isset($_GET['offset']) && is_numeric($_GET['offset']) && $_GET['offset'] > 0) ? $_GET['offset'] : 0;
  $limit = _limit();

  // Serve data from cache
  $items = &drupal_static(__FUNCTION__);
  $cache_cid = "api_concert_reviews_{$offset}_{$limit}";
  if (empty($data)) {
    $cache = cache_get($cache_cid);
    if (is_object($cache) && CACHE_ENABLED && REQUEST_TIME < $cache->expire) {
      $items = $cache->data;
    } else {
      $items = _fetch_concert_reviews_from_db($offset, $limit);
      cache_set($cache_cid, $items, 'cache', (REQUEST_TIME + CACHE_LIFETIME_SECONDS));
    }
  }

  $max = _maximum_concert_reviews();
  $last_offset = $max - ($max % $limit);

  $links = array(
    "next" => "<" . url('api/' . API_VERSION . '/concert_reviews', array('absolute' => TRUE, 'query' => array('offset' => $offset+$limit, 'limit' => $limit))) . ">; rel=\"next\"",
    "last" => "<" . url('api/' . API_VERSION . '/concert_reviews', array('absolute' => TRUE, 'query' => array('offset' => $last_offset, 'limit' => $limit))) . ">; rel=\"last\"",
    "first" => "<" . url('api/' . API_VERSION . '/concert_reviews', array('absolute' => TRUE, 'query' => array('offset' => 0, 'limit' => $limit))) . ">; rel=\"first\"",
  );

  $prev_offset = $offset-$limit;
  if ($prev_offset >= 0) {
    $links['prev'] =  "<" . url('api/' . API_VERSION . '/concert_reviews', array('absolute' => TRUE, 'query' => array('offset' => $prev_offset, 'limit' => $limit))) . ">; rel=\"prev\"";
  }

  drupal_add_http_header('Link', implode(", ", $links));

  drupal_json_output(array(
    "data" => $items
  ));
  drupal_exit();
}

function _api_concerts() {
  drupal_add_http_header('Access-Control-Allow-Methods: ', 'GET');

  if (!isset($_GET['api_key'])) {
    if (!_valid_http_auth()) {
      drupal_exit();
    }
  } else {
    if (!_valid_api_key()) {
      drupal_exit();
    }
  }

  $offset = (isset($_GET['offset']) && is_numeric($_GET['offset']) && $_GET['offset'] > 0) ? $_GET['offset'] : 0;
  $limit = _limit();

  $start_time_after = (isset($_GET['start_time_after']) && is_numeric($_GET['start_time_after']) && $_GET['start_time_after'] > 0) ? $_GET['start_time_after'] : 0;

  // Serve data from cache
  $items = &drupal_static(__FUNCTION__);
  $cache_cid = "api_concerts_{$offset}_{$limit}";
  if (empty($data)) {
    $cache = cache_get($cache_cid);
    if (is_object($cache) && CACHE_ENABLED && REQUEST_TIME < $cache->expire) {
      $items = $cache->data;
    } else {
      $items = _fetch_concerts_from_db($offset, $limit, $start_time_after);
      cache_set($cache_cid, $items, 'cache', (REQUEST_TIME + CACHE_LIFETIME_SECONDS));
    }
  }

  $max = _maximum_concerts();
  $last_offset = $max - ($max % $limit);

  $links = array(
    "next" => "<" . url('api/' . API_VERSION . '/concerts', array('absolute' => TRUE, 'query' => array('offset' => $offset+$limit, 'limit' => $limit))) . ">; rel=\"next\"",
    "last" => "<" . url('api/' . API_VERSION . '/concerts', array('absolute' => TRUE, 'query' => array('offset' => $last_offset, 'limit' => $limit))) . ">; rel=\"last\"",
    "first" => "<" . url('api/' . API_VERSION . '/concerts', array('absolute' => TRUE, 'query' => array('offset' => 0, 'limit' => $limit))) . ">; rel=\"first\"",
  );

  $prev_offset = $offset-$limit;
  if ($prev_offset >= 0) {
    $links['prev'] =  "<" . url('api/' . API_VERSION . '/concerts', array('absolute' => TRUE, 'query' => array('offset' => $prev_offset, 'limit' => $limit))) . ">; rel=\"prev\"";
  }

  drupal_add_http_header('Link', implode(", ", $links));

  drupal_json_output(array(
    "data" => $items
  ));
  drupal_exit();
}

function _api_news() {
  drupal_add_http_header('Access-Control-Allow-Methods: ', 'GET');

  if (!isset($_GET['api_key'])) {
    if (!_valid_http_auth()) {
      drupal_exit();
    }
  } else {
    if (!_valid_api_key()) {
      drupal_exit();
    }
  }

  $offset = (isset($_GET['offset']) && is_numeric($_GET['offset']) && $_GET['offset'] > 0) ? $_GET['offset'] : 0;
  $limit = _limit();

  // Serve data from cache
  $items = &drupal_static(__FUNCTION__);
  $cache_cid = "api_news_{$offset}_{$limit}";
  if (empty($data)) {
    $cache = cache_get($cache_cid);
    if (is_object($cache) && CACHE_ENABLED && REQUEST_TIME < $cache->expire) {
      $items = $cache->data;
    } else {
      $items = _fetch_news_from_db($offset, $limit);
      cache_set($cache_cid, $items, 'cache', (REQUEST_TIME + CACHE_LIFETIME_SECONDS));
    }
  }

  $max = _maximum_news();
  $last_offset = $max - ($max % $limit);

  $links = array(
    "next" => "<" . url('api/' . API_VERSION . '/news', array('absolute' => TRUE, 'query' => array('offset' => $offset+$limit, 'limit' => $limit))) . ">; rel=\"next\"",
    "last" => "<" . url('api/' . API_VERSION . '/news', array('absolute' => TRUE, 'query' => array('offset' => $last_offset, 'limit' => $limit))) . ">; rel=\"last\"",
    "first" => "<" . url('api/' . API_VERSION . '/news', array('absolute' => TRUE, 'query' => array('offset' => 0, 'limit' => $limit))) . ">; rel=\"first\"",
  );

  $prev_offset = $offset-$limit;
  if ($prev_offset >= 0) {
    $links['prev'] =  "<" . url('api/' . API_VERSION . '/news', array('absolute' => TRUE, 'query' => array('offset' => $prev_offset, 'limit' => $limit))) . ">; rel=\"prev\"";
  }

  drupal_add_http_header('Link', implode(", ", $links));

  drupal_json_output(array(
    "data" => $items
  ));
  drupal_exit();
}

function _api_reportages() {
  drupal_add_http_header('Access-Control-Allow-Methods: ', 'GET');

  if (!isset($_GET['api_key'])) {
    if (!_valid_http_auth()) {
      drupal_exit();
    }
  } else {
    if (!_valid_api_key()) {
      drupal_exit();
    }
  }

  $offset = (isset($_GET['offset']) && is_numeric($_GET['offset']) && $_GET['offset'] > 0) ? $_GET['offset'] : 0;
  $limit = _limit();

  // Serve data from cache
  $items = &drupal_static(__FUNCTION__);
  $cache_cid = "api_reportages_{$offset}_{$limit}";
  if (empty($data)) {
    $cache = cache_get($cache_cid);
    if (is_object($cache) && CACHE_ENABLED && REQUEST_TIME < $cache->expire) {
      $items = $cache->data;
    } else {
      $items = _fetch_reportages_from_db($offset, $limit);
      cache_set($cache_cid, $items, 'cache', (REQUEST_TIME + CACHE_LIFETIME_SECONDS));
    }
  }

  $max = _maximum_reportages();
  $last_offset = $max - ($max % $limit);

  $links = array(
    "next" => "<" . url('api/' . API_VERSION . '/reportages', array('absolute' => TRUE, 'query' => array('offset' => $offset+$limit, 'limit' => $limit))) . ">; rel=\"next\"",
    "last" => "<" . url('api/' . API_VERSION . '/reportages', array('absolute' => TRUE, 'query' => array('offset' => $last_offset, 'limit' => $limit))) . ">; rel=\"last\"",
    "first" => "<" . url('api/' . API_VERSION . '/reportages', array('absolute' => TRUE, 'query' => array('offset' => 0, 'limit' => $limit))) . ">; rel=\"first\"",
  );

  $prev_offset = $offset-$limit;
  if ($prev_offset >= 0) {
    $links['prev'] =  "<" . url('api/' . API_VERSION . '/reportages', array('absolute' => TRUE, 'query' => array('offset' => $prev_offset, 'limit' => $limit))) . ">; rel=\"prev\"";
  }

  drupal_add_http_header('Link', implode(", ", $links));

  drupal_json_output(array(
    "data" => $items
  ));
  drupal_exit();
}

function _api_interviews() {
  drupal_add_http_header('Access-Control-Allow-Methods: ', 'GET');

  if (!isset($_GET['api_key'])) {
    if (!_valid_http_auth()) {
      drupal_exit();
    }
  } else {
    if (!_valid_api_key()) {
      drupal_exit();
    }
  }

  $offset = (isset($_GET['offset']) && is_numeric($_GET['offset']) && $_GET['offset'] > 0) ? $_GET['offset'] : 0;
  $limit = _limit();

  // Serve data from cache
  $items = &drupal_static(__FUNCTION__);
  $cache_cid = "api_interviews_{$offset}_{$limit}";
  if (empty($data)) {
    $cache = cache_get($cache_cid);
    if (is_object($cache) && CACHE_ENABLED && REQUEST_TIME < $cache->expire) {
      $items = $cache->data;
    } else {
      $items = _fetch_interviews_from_db($offset, $limit);
      cache_set($cache_cid, $items, 'cache', (REQUEST_TIME + CACHE_LIFETIME_SECONDS));
    }
  }

  $max = _maximum_interviews();
  $last_offset = $max - ($max % $limit);

  $links = array(
    "next" => "<" . url('api/' . API_VERSION . '/interviews', array('absolute' => TRUE, 'query' => array('offset' => $offset+$limit, 'limit' => $limit))) . ">; rel=\"next\"",
    "last" => "<" . url('api/' . API_VERSION . '/interviews', array('absolute' => TRUE, 'query' => array('offset' => $last_offset, 'limit' => $limit))) . ">; rel=\"last\"",
    "first" => "<" . url('api/' . API_VERSION . '/interviews', array('absolute' => TRUE, 'query' => array('offset' => 0, 'limit' => $limit))) . ">; rel=\"first\"",
  );

  $prev_offset = $offset-$limit;
  if ($prev_offset >= 0) {
    $links['prev'] =  "<" . url('api/' . API_VERSION . '/interviews', array('absolute' => TRUE, 'query' => array('offset' => $prev_offset, 'limit' => $limit))) . ">; rel=\"prev\"";
  }

  drupal_add_http_header('Link', implode(", ", $links));

  drupal_json_output(array(
    "data" => $items
  ));
  drupal_exit();
}

function _api_swagger_ui() {
  global $base_url;
  return array(
    '#markup' => '<link rel="stylesheet" type="text/css" href="//unpkg.com/swagger-ui-dist@3/swagger-ui.css" />
    <div id="swagger-ui"></div>
    <script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
    <script type="text/javascript">
    SwaggerUIBundle({
      url: \'' . $base_url . '/api/v1/openapi.yaml\',
      dom_id: \'#swagger-ui\'
    })
    </script>'
  );
}

function _api_openapi() {
  header("content-type:text/yaml;charset=utf-8");
  $openapi_file = drupal_get_path('module', 'api') . "/templates/openapi.yaml";
  print file_get_contents($openapi_file);
}

function _api_genres() {
  drupal_add_http_header('Access-Control-Allow-Methods: ', 'GET');

  if (!isset($_GET['api_key'])) {
    if (!_valid_http_auth()) {
      drupal_exit();
    }
  } else {
    if (!_valid_api_key()) {
      drupal_exit();
    }
  }

  $items = &drupal_static(__FUNCTION__);
  $cache_cid = "api_genres";
  if (empty($data)) {
    $cache = cache_get($cache_cid);
    if (is_object($cache) && CACHE_ENABLED && REQUEST_TIME < $cache->expire) {
      $items = $cache->data;
    } else {
      $items = _fetch_terms_from_db('Genre');
      cache_set($cache_cid, $items, 'cache', (REQUEST_TIME + CACHE_LIFETIME_SECONDS));
    }
  }

  drupal_json_output(array(
    "data" => $items
  ));
  drupal_exit();
}

function _api_venues() {
  drupal_add_http_header('Access-Control-Allow-Methods: ', 'GET');

  if (!isset($_GET['api_key'])) {
    if (!_valid_http_auth()) {
      drupal_exit();
    }
  } else {
    if (!_valid_api_key()) {
      drupal_exit();
    }
  }

  $items = &drupal_static(__FUNCTION__);
  $cache_cid = "api_venues";
  if (empty($data)) {
    $cache = cache_get($cache_cid);
    if (is_object($cache) && CACHE_ENABLED && REQUEST_TIME < $cache->expire) {
      $items = $cache->data;
    } else {
      $items = _fetch_terms_from_db('Venue');
      cache_set($cache_cid, $items, 'cache', (REQUEST_TIME + CACHE_LIFETIME_SECONDS));
    }
  }

  drupal_json_output(array(
    "data" => $items
  ));
  drupal_exit();
}

function _api_reviews() {
  drupal_add_http_header('Access-Control-Allow-Methods: ', 'GET');

  if (!isset($_GET['api_key'])) {
    if (!_valid_http_auth()) {
      drupal_exit();
    }
  } else {
    if (!_valid_api_key()) {
      drupal_exit();
    }
  }

  $offset = (isset($_GET['offset']) && is_numeric($_GET['offset']) && $_GET['offset'] > 0) ? $_GET['offset'] : 0;
  $limit = _limit();

  // Serve data from cache
  $items = &drupal_static(__FUNCTION__);
  $cache_cid = "api_reviews_{$offset}_{$limit}";
  if (empty($data)) {
    $cache = cache_get($cache_cid);
    if (is_object($cache) && CACHE_ENABLED && REQUEST_TIME < $cache->expire) {
      $items = $cache->data;
    } else {
      $items = _fetch_reviews_from_db($offset, $limit);
      cache_set($cache_cid, $items, 'cache', (REQUEST_TIME + CACHE_LIFETIME_SECONDS));
    }
  }

  $max = _maximum_reviews();
  $last_offset = $max - ($max % $limit);

  $links = array(
    "next" => "<" . url('api/' . API_VERSION . '/reviews', array('absolute' => TRUE, 'query' => array('offset' => $offset+$limit, 'limit' => $limit))) . ">; rel=\"next\"",
    "last" => "<" . url('api/' . API_VERSION . '/reviews', array('absolute' => TRUE, 'query' => array('offset' => $last_offset, 'limit' => $limit))) . ">; rel=\"last\"",
    "first" => "<" . url('api/' . API_VERSION . '/reviews', array('absolute' => TRUE, 'query' => array('offset' => 0, 'limit' => $limit))) . ">; rel=\"first\"",
  );

  $prev_offset = $offset-$limit;
  if ($prev_offset >= 0) {
    $links['prev'] =  "<" . url('api/' . API_VERSION . '/reviews', array('absolute' => TRUE, 'query' => array('offset' => $prev_offset, 'limit' => $limit))) . ">; rel=\"prev\"";
  }

  drupal_add_http_header('Link', implode(", ", $links));
  drupal_json_output(array(
    "data" => $items
  ));
  drupal_exit();
}

function _fetch_concert_reviews_from_db($offset, $limit) {
  $sql = "SELECT n.nid, p.published_at
FROM node n 
INNER JOIN publication_date p ON p.nid = n.nid
WHERE n.type = :type AND n.status = :status 
ORDER BY p.published_at DESC 
LIMIT {$offset}, {$limit}";

  $rs = db_query($sql, array(':type' => 'concert_review', ':status' => 1));

  $items = array();
  foreach ($rs as $row) {
    $node = node_load($row->nid);
    $items[] = _output_concert_review($node, $row->published_at);
  }
  return $items;
}

function _fetch_concerts_from_db($offset, $limit, $start_time_after = 0) {
  $sql = "SELECT n.nid, p.published_at
FROM node n 
INNER JOIN publication_date p ON p.nid = n.nid
INNER JOIN field_data_field_event_date e ON e.entity_id = n.nid AND e.bundle = 'concert'
WHERE n.type = :type AND n.status = :status AND e.field_event_date_value > :start_time_after
ORDER BY e.field_event_date_value DESC 
LIMIT {$offset}, {$limit}";

  $rs = db_query($sql, array(':type' => 'concert', ':status' => 1, ':start_time_after' => $start_time_after));

  $items = array();
  foreach ($rs as $row) {
    $node = node_load($row->nid);
    $items[] = _output_concert_node($node, $row->published_at);
  }
  return $items;
}

function _fetch_interviews_from_db($offset, $limit) {
  $sql = "SELECT n.nid, p.published_at
FROM node n 
INNER JOIN publication_date p ON p.nid = n.nid
WHERE n.type = :type AND n.status = :status 
ORDER BY p.published_at DESC 
LIMIT {$offset}, {$limit}";

  $rs = db_query($sql, array(':type' => 'interview', ':status' => 1));

  $items = array();
  foreach ($rs as $row) {
    $node = node_load($row->nid);
    $items[] = _output_interview($node, $row->published_at);
  }
  return $items;
}

function _fetch_news_from_db($offset, $limit) {
  $sql = "SELECT n.nid, p.published_at
FROM node n 
INNER JOIN publication_date p ON p.nid = n.nid
WHERE n.type = :type AND n.status = :status 
ORDER BY p.published_at DESC 
LIMIT {$offset}, {$limit}";

  $rs = db_query($sql, array(':type' => 'news', ':status' => 1));

  $items = array();
  foreach ($rs as $row) {
    $node = node_load($row->nid);
    $items[] = _output_news($node, $row->published_at);
  }
  return $items;
}

function _fetch_reportages_from_db($offset, $limit) {
  $sql = "SELECT n.nid, p.published_at
FROM node n 
INNER JOIN publication_date p ON p.nid = n.nid
WHERE n.type = :type AND n.status = :status 
ORDER BY p.published_at DESC 
LIMIT {$offset}, {$limit}";

  $rs = db_query($sql, array(':type' => 'reportage', ':status' => 1));

  $items = array();
  foreach ($rs as $row) {
    $node = node_load($row->nid);
    $items[] = _output_reportage($node, $row->published_at);
  }
  return $items;
}

function _fetch_reviews_from_db($offset, $limit) {
  $sql = "SELECT n.nid, p.published_at
FROM node n 
INNER JOIN publication_date p ON p.nid = n.nid
WHERE n.type = :type AND n.status = :status 
ORDER BY p.published_at DESC 
LIMIT {$offset}, {$limit}";

  $rs = db_query($sql, array(':type' => 'review', ':status' => 1));

  $items = array();
  foreach ($rs as $row) {
    $node = node_load($row->nid);
    $items[] = _output_review($node, $row->published_at);
  }
  return $items;
}

function _fetch_terms_from_db($vocabulary_machine_name) {
  $vocabulary = taxonomy_vocabulary_machine_name_load($vocabulary_machine_name);
  $t = entity_load('taxonomy_term', FALSE, array('vid' => $vocabulary->vid));

  $items = array();
  foreach ($t as $item) {
    $items[] = array(
      'tid' => (int) $item->tid,
      'title' => $item->name,
      'url' => url('taxonomy/term/' . $item->tid, array('absolute' => TRUE)),
      'descriptionHtml' => (strlen($item->description) > 0) ? $item->description : NULL,
    );
  }
  return $items;
}

function _maximum_reviews() {
  $sql = "SELECT COUNT(n.nid) AS count FROM node n WHERE type = :type AND status = :status";
  $c = db_query($sql, array(':type' => 'review', ':status' => 1))->fetchAssoc();
  return $c['count'];
}

function _maximum_concert_reviews() {
  $sql = "SELECT COUNT(n.nid) AS count FROM node n WHERE type = :type AND status = :status";
  $c = db_query($sql, array(':type' => 'concert_review', ':status' => 1))->fetchAssoc();
  return $c['count'];
}

function _maximum_concerts() {
  $sql = "SELECT COUNT(n.nid) AS count FROM node n WHERE type = :type AND status = :status";
  $c = db_query($sql, array(':type' => 'concerts', ':status' => 1))->fetchAssoc();
  return $c['count'];
}

function _maximum_interviews() {
  $sql = "SELECT COUNT(n.nid) AS count FROM node n WHERE type = :type AND status = :status";
  $c = db_query($sql, array(':type' => 'interview', ':status' => 1))->fetchAssoc();
  return $c['count'];
}

function _maximum_news() {
  $sql = "SELECT COUNT(n.nid) AS count FROM node n WHERE type = :type AND status = :status";
  $c = db_query($sql, array(':type' => 'news', ':status' => 1))->fetchAssoc();
  return $c['count'];
}

function _maximum_reportages() {
  $sql = "SELECT COUNT(n.nid) AS count FROM node n WHERE type = :type AND status = :status";
  $c = db_query($sql, array(':type' => 'reportage', ':status' => 1))->fetchAssoc();
  return $c['count'];
}

function _api_review($nid) {
  _handle_single_node($nid, 'review', '_output_review');
}

function _api_concert_review($nid) {
  _handle_single_node($nid, 'concert_review', '_output_concert_review');
}

function _api_concert($nid) {
  _handle_single_node($nid, 'concert', '_output_concert_node');
}

function _api_interview($nid) {
  _handle_single_node($nid, 'interview', '_output_interview');
}

function _api_news_story($nid) {
  _handle_single_node($nid, 'news', '_output_news');
}

function _api_reportage($nid) {
  _handle_single_node($nid, 'reportage', '_output_reportage');
}

function _api_artist($nid) {
  _handle_single_node($nid, 'artist', '_output_artist_detailed');
}

function _api_genre($tid) {
  _handle_single_term($tid, 'genre', '_output_genre_detailed');
}

function _api_venue($tid) {
  _handle_single_term($tid, 'venue', '_output_venue_detailed');
}

function _handle_single_node($nid, $type, $render_function) {
  drupal_add_http_header('Access-Control-Allow-Methods: ', 'GET');

  if (!isset($_GET['api_key'])) {
    if (!_valid_http_auth()) {
      drupal_exit();
    }
  } else {
    if (!_valid_api_key()) {
      drupal_exit();
    }
  }

  if (!is_numeric($nid)) {
    drupal_add_http_header('Status', '400 Bad Request');
    drupal_json_output(array(
      "errors" => array(
        array(
          "code" => 4,
          "message" => "The provided key parameter must be numeric."
        )
      )
    ));
    drupal_exit();
  }

  $node = node_load($nid);
  if (!is_object($node) || $node->type != $type) {
    drupal_add_http_header('Status', '404 Not Found');
    drupal_json_output(array(
      "errors" => array(
        array(
          "code" => 5,
          "message" => "Invalid resource specified."
        )
      )
    ));
    drupal_exit();
  }

  $p = db_query("SELECT published_at FROM publication_date WHERE nid = :nid", array(':nid' => $node->nid))->fetchAssoc();

  // Serve data from cache
  $item = &drupal_static(__FUNCTION__);
  $cache_cid = "api_single_node_{$type}_{$nid}";
  $cache = cache_get($cache_cid);
  if (is_object($cache) && CACHE_ENABLED && REQUEST_TIME < $cache->expire) {
    $item = $cache->data;
  } else {
    $item = $render_function($node, $p['published_at']);
    cache_set($cache_cid, $item, 'cache', (REQUEST_TIME + CACHE_LIFETIME_SECONDS));
  }

  drupal_json_output(array(
    "data" => $item
  ));
  drupal_exit();
}

function _handle_single_term($tid, $vocabulary, $render_function) {
  drupal_add_http_header('Access-Control-Allow-Methods: ', 'GET');

  if (!isset($_GET['api_key'])) {
    if (!_valid_http_auth()) {
      drupal_exit();
    }
  } else {
    if (!_valid_api_key()) {
      drupal_exit();
    }
  }

  if (!is_numeric($tid)) {
    drupal_add_http_header('Status', '400 Bad Request');
    drupal_json_output(array(
      "errors" => array(
        array(
          "code" => 4,
          "message" => "The provided key parameter must be numeric."
        )
      )
    ));
    drupal_exit();
  }

  $term = taxonomy_term_load($tid);
  if (!is_object($term) || $term->vocabulary_machine_name != $vocabulary) {
    drupal_add_http_header('Status', '404 Not Found');
    drupal_json_output(array(
      "errors" => array(
        array(
          "code" => 5,
          "message" => "Invalid resource specified."
        )
      )
    ));
    drupal_exit();
  }

  // Serve data from cache
  $item = &drupal_static(__FUNCTION__);
  $cache_cid = "api_single_term_{$vocabulary}_{$tid}";
  $cache = cache_get($cache_cid);
  if (is_object($cache) && CACHE_ENABLED && REQUEST_TIME < $cache->expire) {
    $item = $cache->data;
  } else {
    $item = $render_function($term);
    cache_set($cache_cid, $item, 'cache', (REQUEST_TIME + CACHE_LIFETIME_SECONDS));
  }

  drupal_json_output(array(
    "data" => $item
  ));
  drupal_exit();
}