language: node_js
node_js:
- '6'
install:
- npm install
cache:
  directories:
  - node_modules
script: gulp deploy --user $FTP_USER --password $FTP_PASSWORD --branch $TRAVIS_BRANCH
env:
  global:
  - secure: FGJ5/b00+4Niwhr24V1DhRYuHl0VYhDuXzjN9ZTvrgGUBr1kvKn3VH4+Ex2GyipuhTMWpPwvRzWKQgYlbclZt8QFCpQsxu88NxUVGRuC4RYBx4OsBgjhOkQZiSripr+t8KNtTQA4SZN76n55VpgZOeExxyBjQocud6WA4RZM5c7gF88Sxg9jCWwdge8IQsmQuW5TW60C192Ba7mpkjWT16tL695qCW1M4lehpc4eFs5HmDQel/PfFPLSdPsUMXZkDIotfwYpEojgGXTtADCmWfjh2mXrgV242x9kDxhTqM+oWgwXqQZW9HgnUgo40BvsFBJtkXGp4UE+nLcsljjPldgLLuynQDhqS/xcPxM+t3UUaalVH0NBGe0vQ9HeD/2DZVC5mGrKQCOKSKGEcFrVS/KkPa3gwSwWH3rjj5NzMFl0PShF3Onx6ODGN4SreDpkKSHIH0mhsBdHME5B/qDidS1xRu5fd0r8gS9/VSEuW8/N8Vm1a8VpIBZeWBL9m5t0sfZfXdV0J1cnZw0WfRAHTfhLpU/9h95I3iOZ4cjj3wgWNHTJFm8kPHR3jiTGUnISjR+bDUYrmjkYtgAjfKqXovO0Xz700hDxvzB2ipdAdN2Crf/nhVvZRKisdBZwgJIAlbcI9Qq5AkywIZAyb0oh4IxABOpW+qPFe6Svynu398k=
  - secure: eyiQt4GuB5+Jj1JhORq+un3vzIjQdzD0PlQt32zTHznHwQymXcFoDgxaxSlChPtRMgxAa94cC/G/Ut7qf/jNX8+7MxHQoRBARP/6BbnpUN3gWiZgY2JE27DTyMlpHqYSxXzrDC7Z2f/m1MF7+fEVNk3z0Kok3bO9v2WQYD9qMJjXsXoSjuqBzyDrH/kB4oKLisrb37nqSEM0ku4MXBcvRGHiJ4PYMqk6TFVEIdxmtPvWm7j7ZOw5o13XdMpD6JUFoAyFTYj95IICMS3eI97aS9LlkuSZQVe+MFgLEzP/c2WkGCb5kPjs9UFDYSZFaMpxFHhaU5RgO8BN6k9h9GP4B8Rbyn5nwNHu05hGRgAB9/0xBtPwo4/Ep8b0p6REQoIzv6EkiOsJwFcEY7em8bsQyz/JiMqZLJwJR7RVWCFncV9ZJZyOJdKhpntfYBrjkE8AqBAkRuVNclcey+kfYXvw79FzYSUnJkYK/6E8IBOrBFKTbwoTPPj61bwZ/NyW6jxfg1TzA6qq6apIc/B9oI6/myEWEoFXVEQS5EIJS2ruocMR0jkiEyQNC+d8DgAuOP3K0jZOXkG4BpLsHF6o6KG47tNN+F1lOzMfuE0x9LEmEyEXvW7Cq6TWDEiHar5QBbgXJx7OKQYM/9j+OlfuUe3Yw7qTlhvRu+Rl8ioivf0Br88=
