version: '3.5'

services:
  webserver:
    build:
      context: './docker/webserver'
    image: heavymetaldk_web
    container_name: "${PROJECT_NAME}_server"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./www:/var/www/html"
    links:
      - db:mysql
  php-myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_phpmyadmin"
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    links:
      - db:mysql
  db:
    image: mysql:5.7
    container_name: "${PROJECT_NAME}_mysql"
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME