<?php

require_once('frontpage.country.inc');

/**
 * Implements hook_block_info().
 */
function frontpage_block_info() {
  $blocks['block-frontpage'] = array(
    'info' => t('Frontpage block'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function frontpage_block_view($delta) {

  $block = array();
  switch ($delta) {
    case 'block-frontpage':
      $block['subject'] = t('Frontpage block');
      $block['content'] = theme('block-frontpage', array('content' => _frontpage_contents()));
      break;
  }
  return $block;
}

/**
 * Implements hook_theme().
 */
function frontpage_theme() {
  return array(
    'block-frontpage' => array(
      'template' => 'block--frontpage',
      'variables' => array('form' => NULL),
      'path' => drupal_get_path('module', 'frontpage'),
    ),
  );
}

/**
 * Fetches the frontpage block contents from the database.
 */
function _frontpage_contents() {

  $promoted = _promoted_content();
  $country = _country_content($promoted['nid']);
  $additional = _additional_content($promoted['nid']);

  $contents = array();
  $contents['promoted'] = $promoted['nodes'];
  $contents['danish'] = $country['danish'];
  $contents['danish_concerts'] = _concerts('da');
  $contents['international'] = $country['international'];
  $contents['additional'] = $additional;


  return $contents;
}

function _content_types() {
  return array(
    'review',
    'reportage',
    'poll',
    'page',
    'blog',
    'interview',
    'concert_review',
    'contest',
    'news',
    'gallery'
  );
}

function _get_classes($c) {
  $classes = NULL;
  if ($c % 3 == 0) {
    $classes = 'first';
  }
  if ($c % 3 == 2) {
    $classes = 'last';
  }
  return $classes;
}

function _promoted_content() {
  $sql = "SELECT n.nid ";
  $sql.= "FROM node n ";
  $sql.= "INNER JOIN publication_date d ON d.nid = n.nid ";
  $sql.= "WHERE n.status = :status AND n.promote = :promote AND n.sticky = :sticky AND n.type IN (:types) ";
  $sql.= "ORDER BY d.published_at DESC ";
  $sql.= "LIMIT 4 ";
  $rs = db_query($sql, array(':status' => 1, ':promote' => 1, ':sticky' => 1, ':types' => _content_types()));

  $nodes = array();
  foreach ($rs as $row) {
    $node = node_load($row->nid);
    $node_view = node_view($node, 'topfront');
    $nodes['nodes'][] = array(
      'view' => render($node_view),
      'classes' => NULL
    );
    $nodes['nid'][] = $row->nid;
  }
  return $nodes;
}

/**
 * Excludes content that is more than 2 months old.
 */
function _additional_content($exclude) {
  $date = strtotime("-2 months");
  $types = array(
    'contest',
    'news',
    'page',
    'poll'
  );

  $sql = "SELECT n.nid ";
  $sql.= "FROM node n ";
  $sql.= "INNER JOIN publication_date d ON d.nid = n.nid ";
  $sql.= "WHERE n.status = :status AND n.promote = :promote AND n.type IN (:types) AND n.nid NOT IN (:exclude) AND d.published_at > :date ";
  $sql.= "ORDER BY d.published_at DESC ";
  $sql.= "LIMIT 5 ";
  $rs = db_query($sql, array(':status' => 1, ':promote' => 1, ':types' => $types, ':exclude' => $exclude, ':date' => $date));

  $nodes = array();
  foreach ($rs as $row) {
    $node = node_load($row->nid);
    $node_view = node_view($node, 'teaser');
    $nodes[] = array(
      'view' => render($node_view),
      'classes' => NULL
    );
  }
  return $nodes;
}

function _concerts($country = 'da') {
  $num_concerts = 5;
  $band_limit = 3;

  $query = db_select('node', 'n');
  $query->fields('n', array('nid'));
  $query->join('field_data_field_event_date', 'd', 'd.entity_id = n.nid');
  $query->condition('n.type', 'concert');
  $query->condition('n.status', '1');
  $query->condition('d.field_event_date_value', time(), '>');
  $query->orderBy('d.field_event_date_value', 'ASC');
  $query->range(0, $num_concerts);

  $rs = $query->execute();
  $concerts = array();
  foreach ($rs as $row) {
    $node = node_load($row->nid);

    $artist_string = '';
    if ($node->field_is_festival[LANGUAGE_NONE][0]['value'] == 1) {
      $artist_string = "<strong>" . l($node->title, 'node/' . $node->nid, array('absolute' => TRUE)) . "</strong>: ";
    }
    $artists = array();
    for ($i = 0; $i < $band_limit; $i++) {
      if (isset($node->field_artists[LANGUAGE_NONE][$i])) {
        $artists[] = l(_get_artist_name($node->field_artists[LANGUAGE_NONE][$i]['target_id']), 'node/' . $node->field_artists[LANGUAGE_NONE][$i]['target_id'], array('absolute' => TRUE));
      }
    }
    $artist_string.= implode(", ", $artists);
    if (count($node->field_artists[LANGUAGE_NONE]) > $band_limit) {
      $artist_string .= ", m.fl.";
    }

    $node->artist_string = $artist_string;
    $concerts[] = $node;
  };
}

function _country_content($exclude) {
  $limit = 12;
  $nodes = array(
    'danish' => array(),
    'international' => array()
  );

  $i = 0;
  $continue = true;
  while ($continue) {

    $items = _fetch_items($exclude, $i * 24);
    if (count($items) == 0) {
      break;
    }

    foreach ($items as $item) {
      if ($item['danish'] && count($nodes['danish']) < $limit) {
        $item['classes'] = _get_classes(count($nodes['danish']));
        $nodes['danish'][] = $item;
      } else if (!$item['danish'] && count($nodes['international']) < $limit) {
        $item['classes'] = _get_classes(count($nodes['international']));
        $nodes['international'][] = $item;
      }
    }
    $i++;

    if (count($nodes['danish']) == $limit && count($nodes['international']) == $limit) {
      $continue = false;
    }
  }
  return $nodes;
}

function _fetch_items($exclude, $offset = 0) {
  $types = array('review', 'concert_review', 'reportage', 'interview', 'blog');

  $sql = "SELECT n.nid, n.type ";
  $sql.= "FROM node n ";
  $sql.= "INNER JOIN publication_date d ON d.nid = n.nid ";
  $sql.= "WHERE n.status = :status AND n.promote = :promote AND n.type IN (:types) AND n.nid NOT IN (:exclude) ";
  $sql.= "ORDER BY d.published_at DESC ";
  $sql.= "LIMIT 24 OFFSET " . $offset;

  $rs = db_query($sql, array(':status' => 1, ':promote' => 1, ':types' => $types, ':exclude' => $exclude));
  $items = array();
  foreach ($rs as $row) {
    $node = node_load($row->nid);
    $node_view = node_view($node, 'focus');

    $items[] = array(
      'nid' => $row->nid,
      'view' => render($node_view),
      'danish' => _is_danish($row->nid, $row->type)
    );
  }
  return $items;
}
